defaultFont = Sans 18

@activeBG = #162d50
@nonActiveBG = #424548
@hoverBG = #214478
@selectableBG = #1f2836

Button.background = @activeBG
Button.disabledBackground = @nonActiveBG
Button.hoverBackground = @hoverBG

TabbedPane.background = @selectableBG
TabbedPane.selectedBackground = @activeBG
TabbedPane.hoverBackground = @hoverBG
TabbedPane.focusColor = @activeBG
